### ISSUE TITLE
" Cannot convert non-finite values" error

### ISSUE THREAD

**Issue by drelo** [corydunnlab/SequenceBouncer#3]
Dear Cory, 

This software  caught my attention since  I was looking a similar tool. Does this program accept amino acids as input?
I installed it through _conda_ trying to minimize the errors while installing, I used this

```
conda create --name bouncer biopython=1.78 pandas=1.2.4 numpy=1.20.2 matplotlib=3.4.2 python=3.9.4
conda activate bouncer
```

I have an error trying this, but this error might be trivial if this doesn't support AA. Thanks in advance!

`python ./SequenceBouncer/SequenceBouncer.py -i seq.fa `

```

SequenceBouncer: A method to remove outlier entries from a multiple sequence alignment

Cory Dunn
University of Helsinki
cory.dunn@helsinki.fi
Version: 1.23
Please cite DOI: 10.1101/2020.11.24.395459
___

Analyzing 'seq.fa'.
Flags are --IQR_coefficient: 1.0, -subsample_size: 173, --gap_percent_cut: 2.0
Input alignment length is: 131 characters.
Input alignment depth is: 173 sequences.
Generating sequence dataframe.
Traceback (most recent call last):
  File "/home/andrespara/andres/sulfide/BOUNCER/./SequenceBouncer/SequenceBouncer.py", line 162, in <module>
    sequence_dataframe = sequence_dataframe.astype('int8')
  File "/home/andrespara/anaconda3/envs/bouncer/lib/python3.9/site-packages/pandas/core/generic.py", line 5877, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "/home/andrespara/anaconda3/envs/bouncer/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 631, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "/home/andrespara/anaconda3/envs/bouncer/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 427, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/andrespara/anaconda3/envs/bouncer/lib/python3.9/site-packages/pandas/core/internals/blocks.py", line 673, in astype
    values = astype_nansafe(vals1d, dtype, copy=True)
  File "/home/andrespara/anaconda3/envs/bouncer/lib/python3.9/site-packages/pandas/core/dtypes/cast.py", line 1068, in astype_nansafe
    raise ValueError("Cannot convert non-finite values (NA or inf) to integer")
ValueError: Cannot convert non-finite values (NA or inf) to integer
```
[seq.fa.txt](https://github.com/corydunnlab/SequenceBouncer/files/7367091/seq.fa.txt)

**Comment by corydunnlab** [comment]
Hi drelo - 

The input has to be a multiple sequence alignment, but your input FASTA is not yet aligned.

It is a good reminder, however, for me to add this possible error to a later iteration of the software (check sequence lengths and make sure they are all the same).

Amino acid alignments should be no problem.

All the best,
Cory

**Comment by drelo** [comment]
Oh my bad I thought I could use it to exclude X sequences before aligning
but it makes sense using 'only' an alignment first. I clearly rushed trying
to use this but now with the alignment it works! Now I will tune some
parameters but the output looks good with a -g 50 for example
Thanks for the help
